mode: server

replicaCount: 1

podLabels:
  iperf.opencost.io/group: demo

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        iperf.opencost.io/group: demo

service:
  type: ClusterIP
  port: 5201
  targetPort: 5201

server:
  port: 5201
  intervalSeconds: 5
  forceFlush: true
  verbose: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
